### ISSUE TITLE
Pseudolocalization bootloops the system (workaround found)

### ISSUE THREAD

**Issue by A1Asriel** [crdroidandroid/android_device_xiaomi_vayu#2]
## Expected Behavior
The localization is changed to "English one two" correctly.

## Current Behavior
The phone crashes instantly and makes itself bootloop (stucks on the boot animation).

## Steps to Reproduce
1. Open Settings > System > Languages & input > Languages.
2. Click Add a language and choose "[English one two] ([Pseudo-Accents one two])" language.
3. Drag it to the top of the current languages.
4. The system crashes instantly and can no longer boot.

## Workaround

In case if you encounter this issue, you can edit the configuration manually, although it's a bit tricky. You have to be able to access the phone's filesystem from a PC through recovery environment and ADB. The computer needs to have Python and Java Development Kit installed to use some specific tools.
1. Pull `/data/system/users/0/settings_system.xml` to the computer. **Make a backup of this file in case if anything goes wrong!**
2. Get `android-bits/ccl_abx/ccl_abx.py` file from [this](https://github.com/cclgroupltd/android-bits) repository.
3. Follow the instructions inside `android-bits/ccl_abx` folder to uncompress the XML file you got from the phone. Example: `py ccl_abx.py settings_system.xml -mr > settings_system_uncompressed.xml`
4. Remove the `<root></root>` tag and replace all the `en-XA` entries with any other valid language code in the new file (not tested if you can remove it instead of editing).
5. Use the `makeabx` tool from the mentioned repository to compress the edited file back. You have to compile the tool with JDK.
6. Rename the new file to `settings_system.xml` (make sure that you did a backup of the original file) and push it back to the phone, replacing the original file there.
7. Reboot into the system. It should boot properly now.

**Comment by neobuddy89** [comment]
This language breaks code at multiple places. 
Is this official language by google?

**Comment by SigmaTel71** [comment]
> This language breaks code at multiple places. 
> Is this official language by google?

It is. Here's a screenshot from another device running Android 8.1 as official firmware.

![Screenshot_20220624-094338.png](https://user-images.githubusercontent.com/17989678/175478289-a1700276-1116-4525-b33c-048107d7709a.png)![Screenshot_20220624-094610.png](https://user-images.githubusercontent.com/17989678/175478657-4f825ea4-1669-4ff9-965d-0273d597e069.png)

**Comment by neobuddy89** [comment]
Any 12.1 ROM working with this langugage.

The issue is - all strings are converted  to this language
e.g.

06-24 12:51:19.436  1487  3426 W ActivityManager: Unable to start service Intent { act=android.service.smartspace.SmartspaceService cmp=[çöḿ.ĝööĝļé.åñðŕöîð.åš/çöḿ.ĝööĝļé.åñðŕöîð.åþþš.ḿîþĥöñé.åîåî.åþþ.ÅîÅîŠḿåŕţšþåçéŠéŕVîçé one two three four five six seven eight nine] } U=0: not found

**Comment by A1Asriel** [comment]
This is weird. The absence of this tool restricts developers from properly testing their applications.
