### ISSUE TITLE
Issue granting SAF access to any app

### ISSUE THREAD

**Issue by SledgeSune** [crdroidandroid/android_device_xiaomi_vayu#8]
## Issue

When trying to grant Storage Access Framework access, com.android.documentsui (Files) only returns a blank Recents [page](https://github.com/user-attachments/assets/e085a719-f9c0-4a01-89bf-6b059ed6d026)
This happens with any app, the provided example happened when trying to [access](https://github.com/user-attachments/assets/72b49c8e-3928-4dcc-925f-ba4093d952b8) Android/data/[app.name] folder with [Amaze](https://github.com/TeamAmaze/AmazeFileManager)
Can't say for sure, but Im almost certain the problem first happened when i first start using crdroid

## What Ive tried

I have:
- Cleared Dalvik Cache
- Cleared Files data
- Hidden root from Files
- Uninstalling and Reinstalling Files (with ```adb shell cmd package install-existing com.android.documentsui```)
- Read somewhere it was an issue with MiXExplorer, so uninstalled it.
- Rebooting after every step

### Device
Poco X3 Pro, on crDroid 10.9
com.android.documentsui version 14 (34)

**Comment by gwolf2u** [comment]
please use issue_tracker
